import PageLayout from '../components/PageLayout';
import PageHero from '../components/PageHero';
import Button from '../components/Button';
import SEO from '../components/SEO';
import { getBreadcrumbSchema } from '../utils/structuredData';
import { Link } from 'react-router-dom';

function MobilityTraining() {
  const breadcrumbs = [
    { name: 'Home', url: '/' },
    { name: 'Services', url: '/services' },
    { name: 'Mobility Training', url: '/mobility-training' }
  ];

  return (
    <PageLayout>
      <SEO 
        title="Mobility Training Santa Cruz | Flexibility & Movement Quality"
        description="Improve mobility, flexibility, and movement quality through intelligent training. Not just stretching, real functional mobility in Santa Cruz."
        keywords="mobility training santa cruz, flexibility training, movement quality, functional mobility, mobility coach"
        structuredData={getBreadcrumbSchema(breadcrumbs)}
      />
      
      <PageHero 
        imageSrc="/training-hero.jpg"
        title="Mobility Training"
        subtitle="Real flexibility that translates to how you move"
      />


      <div className="bg-white py-12 px-6">
        <div className="max-w-4xl mx-auto">
          
          <div className="mb-16">
            <h2 className="text-3xl font-heading text-primary mb-6">
              Stretching Isn't Working. Try Actual Mobility.
            </h2>
            <p className="text-xl text-neutralDark/80 leading-relaxed mb-6">
              You stretch every day. Foam roll religiously. Maybe even do yoga. But you're still tight. Can't squat deep. Struggle with overhead positions. Feel restricted in your movement.
            </p>
            <p className="text-xl text-neutralDark/80 leading-relaxed mb-6">
              That's because flexibility and mobility aren't the same thing. You can be flexible (passive range of motion) but not mobile (active, usable range of motion with control).
            </p>
            <p className="text-xl text-accent font-semibold">
              Mobility is flexibility you can actually use.
            </p>
          </div>

          <div className="mb-16 bg-sage/5 rounded-2xl p-8">
            <h2 className="text-3xl font-heading text-primary mb-6">
              Flexibility vs. Mobility
            </h2>
            
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-white rounded-xl p-6">
                <h3 className="text-xl font-semibold text-neutralDark mb-3">
                  Flexibility (Passive)
                </h3>
                <ul className="space-y-2 text-neutralDark/80">
                  <li>• How far you can stretch</li>
                  <li>• Requires external force</li>
                  <li>• Often doesn't transfer to movement</li>
                  <li>• Can actually create instability</li>
                  <li>• Example: Touching your toes in a stretch</li>
                </ul>
              </div>

              <div className="bg-white rounded-xl p-6">
                <h3 className="text-xl font-semibold text-neutralDark mb-3">
                  Mobility (Active)
                </h3>
                <ul className="space-y-2 text-neutralDark/80">
                  <li>• Range you can control</li>
                  <li>• Generated by your muscles</li>
                  <li>• Directly improves function</li>
                  <li>• Builds stability in range</li>
                  <li>• Example: Deep squat with control</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="mb-16">
            <h2 className="text-3xl font-heading text-primary mb-6">
              What Limits Mobility?
            </h2>
            
            <div className="space-y-6">
              <div className="border-l-4 border-sage pl-6">
                <h3 className="text-xl font-semibold text-neutralDark mb-2">
                  Fascial Restrictions
                </h3>
                <p className="text-neutralDark/80">
                  Tight, dense fascia physically limits how far joints can move. No amount of stretching fully addresses this. You need hands-on fascial work to create lasting change in tissue quality.
                </p>
              </div>

              <div className="border-l-4 border-accent pl-6">
                <h3 className="text-xl font-semibold text-neutralDark mb-2">
                  Motor Control Issues
                </h3>
                <p className="text-neutralDark/80">
                  Your nervous system might not know how to access or control certain ranges. You have the physical capacity, but not the neurological control. This requires motor learning, not stretching.
                </p>
              </div>

              <div className="border-l-4 border-primary pl-6">
                <h3 className="text-xl font-semibold text-neutralDark mb-2">
                  Weakness in Range
                </h3>
                <p className="text-neutralDark/80">
                  Your body restricts ranges where you're weak. If you can't produce force in a position, your nervous system won't let you go there. You need to build strength through full ranges.
                </p>
              </div>

              <div className="border-l-4 border-highlight pl-6">
                <h3 className="text-xl font-semibold text-neutralDark mb-2">
                  Joint Restrictions
                </h3>
                <p className="text-neutralDark/80">
                  Sometimes joints themselves don't move properly due to capsular tightness or poor positioning. This needs specific joint mobilization, not muscle stretching.
                </p>
              </div>

              <div className="border-l-4 border-sage pl-6">
                <h3 className="text-xl font-semibold text-neutralDark mb-2">
                  Movement Pattern Issues
                </h3>
                <p className="text-neutralDark/80">
                  You might have the mobility but not know how to use it in actual movement. You need to integrate new ranges into functional patterns.
                </p>
              </div>
            </div>
          </div>

          <div className="mb-16 bg-primary/5 rounded-2xl p-8">
            <h2 className="text-2xl font-heading text-primary mb-4">
              My Approach to Mobility Training
            </h2>

            <div className="space-y-6">
              <div>
                <h3 className="text-xl font-semibold text-neutralDark mb-3">
                  1. Release Restrictions (Structural Integration)
                </h3>
                <ul className="space-y-2 text-neutralDark/80 ml-6">
                  <li>• Hands-on fascial work to create tissue quality</li>
                  <li>• Address actual physical limitations</li>
                  <li>• Create space in joints</li>
                  <li>• Restore natural movement capacity</li>
                </ul>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-neutralDark mb-3">
                  2. Build Control (Movement Training)
                </h3>
                <ul className="space-y-2 text-neutralDark/80 ml-6">
                  <li>• Controlled articular rotations (CARs)</li>
                  <li>• Progressive angular isometrics (PAILs/RAILs)</li>
                  <li>• Eccentric training in new ranges</li>
                  <li>• Kinstretch and FRC principles</li>
                  <li>• Active mobility drills</li>
                </ul>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-neutralDark mb-3">
                  3. Integrate Into Movement
                </h3>
                <ul className="space-y-2 text-neutralDark/80 ml-6">
                  <li>• Practice using new ranges in real patterns</li>
                  <li>• Train transitions between positions</li>
                  <li>• Build strength through full ROM</li>
                  <li>• Make mobility functional, not just impressive</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="mb-16">
            <h2 className="text-3xl font-heading text-primary mb-6">
              Key Areas We Work On
            </h2>
            
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-white border-2 border-neutralLight rounded-xl p-6">
                <h3 className="text-lg font-semibold text-neutralDark mb-3">
                  Ankle Mobility
                </h3>
                <p className="text-neutralDark/80 mb-2">
                  Essential for squatting, running, and walking. Most people have severely limited dorsiflexion.
                </p>
                <p className="text-neutralDark/70 text-sm">
                  Tight calves, restricted joint capsule, poor foot mechanics
                </p>
              </div>

              <div className="bg-white border-2 border-neutralLight rounded-xl p-6">
                <h3 className="text-lg font-semibold text-neutralDark mb-3">
                  Hip Mobility
                </h3>
                <p className="text-neutralDark/80 mb-2">
                  Critical for everything. Flexion, extension, internal/external rotation.
                </p>
                <p className="text-neutralDark/70 text-sm">
                  Tight hip flexors, restricted capsule, weak glutes
                </p>
              </div>

              <div className="bg-white border-2 border-neutralLight rounded-xl p-6">
                <h3 className="text-lg font-semibold text-neutralDark mb-3">
                  Thoracic Spine Rotation
                </h3>
                <p className="text-neutralDark/80 mb-2">
                  Needed for throwing, swinging, turning. Most people are locked up here.
                </p>
                <p className="text-neutralDark/70 text-sm">
                  Stiff mid-back, poor rib mobility, desk posture
                </p>
              </div>

              <div className="bg-white border-2 border-neutralLight rounded-xl p-6">
                <h3 className="text-lg font-semibold text-neutralDark mb-3">
                  Shoulder Mobility
                </h3>
                <p className="text-neutralDark/80 mb-2">
                  Overhead range, internal/external rotation for reaching and lifting.
                </p>
                <p className="text-neutralDark/70 text-sm">
                  Tight chest, restricted capsule, poor scapular control
                </p>
              </div>

              <div className="bg-white border-2 border-neutralLight rounded-xl p-6">
                <h3 className="text-lg font-semibold text-neutralDark mb-3">
                  Spine Mobility
                </h3>
                <p className="text-neutralDark/80 mb-2">
                  Flexion, extension, lateral flexion, rotation. Your spine should move.
                </p>
                <p className="text-neutralDark/70 text-sm">
                  Stiff back, fear of movement, protective patterns
                </p>
              </div>

              <div className="bg-white border-2 border-neutralLight rounded-xl p-6">
                <h3 className="text-lg font-semibold text-neutralDark mb-3">
                  Wrist & Hand Mobility
                </h3>
                <p className="text-neutralDark/80 mb-2">
                  Often forgotten but crucial for pressing, gripping, weight-bearing.
                </p>
                <p className="text-neutralDark/70 text-sm">
                  Tight forearms, desk work, lack of varied hand positions
                </p>
              </div>
            </div>
          </div>

          <div className="mb-16">
            <h2 className="text-3xl font-heading text-primary mb-6">
              Who Benefits from Mobility Training
            </h2>
            <div className="grid md:grid-cols-2 gap-4 text-neutralDark/80">
              <div>✓ Athletes wanting better performance</div>
              <div>✓ People feeling "tight" all the time</div>
              <div>✓ Anyone with limited range of motion</div>
              <div>✓ Desk workers with stiff bodies</div>
              <div>✓ Aging adults losing mobility</div>
              <div>✓ Post-injury rehab</div>
              <div>✓ Anyone wanting to move better</div>
              <div>✓ People frustrated with stretching</div>
            </div>
          </div>

          <div className="border-l-4 border-accent pl-6 mb-16">
            <h2 className="text-2xl font-heading text-primary mb-4">
              Results You Can Expect
            </h2>
            <p className="text-lg text-neutralDark/80 leading-relaxed mb-4">
              Real mobility takes time to build (weeks to months, not days). But the changes are lasting because we're not just temporarily stretching, we're building actual motor control and tissue quality.
            </p>
            <p className="text-lg text-neutralDark/80 leading-relaxed">
              You'll move better in daily life, perform better in your sport, and feel less restricted in your body. That's the goal.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <Button to="/consult" variant="primary" size="lg" fullWidth>
              Schedule Free Consultation
            </Button>
            <Button to="/packages" variant="outline" size="lg" fullWidth>
              View Training Programs
            </Button>
          </div>
          {/* Related Pages */}
          <div className="mt-12 pt-8 border-t border-neutralDark/20 text-center">
            <p className="text-sm text-neutralDark/70 mb-4">Related Topics:</p>
            <div className="flex flex-wrap gap-3 justify-center">
              <Link to="/movement-training" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Movement Training Hub
              </Link>
              <Link to="/sports-performance" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Sports Performance Hub
              </Link>
              <Link to="/fascial-release" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Fascial Release
              </Link>
              <Link to="/hip-pain-treatment" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Hip Pain Treatment
              </Link>
              <Link to="/knee-pain-treatment" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Knee Pain Treatment
              </Link>
              <Link to="/shoulder-pain-relief" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Shoulder Pain Relief
              </Link>
              <Link to="/cyclists-and-runners" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Cyclists & Runners
              </Link>
              <Link to="/athletic-performance" className="text-sm px-4 py-2 bg-sage/10 text-primary rounded-lg hover:bg-sage/20 transition">
                Athletic Performance
              </Link>
            </div>
          </div>

        </div>
      </div>
    </PageLayout>
  );
}

export default MobilityTraining;
